// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tradecorp.Infrastructure.Data;

#nullable disable

namespace Tradecorp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.AgendaPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CicloPagoId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CicloPagoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("AgendaPagos", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.AsignacionDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AsignacionId")
                        .HasColumnType("integer");

                    b.Property<int>("PagoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AsignacionId");

                    b.HasIndex("PagoId")
                        .IsUnique();

                    b.ToTable("AsignacionDetalle", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.AsignacionPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BancoId")
                        .HasColumnType("integer");

                    b.Property<int>("CicloPagoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("Jornada")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TipoPago")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BancoId");

                    b.HasIndex("CicloPagoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AsignacionesPago", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.AuditoriaContrato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Observacion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("ValorAnterior")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("ValorNuevo")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditoriaContratos", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.Banco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Bancos", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.CalculoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CicloPagoId")
                        .HasColumnType("integer");

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<int>("DiasCalculados")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaCorte")
                        .HasColumnType("date");

                    b.Property<decimal>("MontoCalculado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CicloPagoId");

                    b.HasIndex("ContratoId", "FechaCorte")
                        .IsUnique();

                    b.ToTable("CalculoPagos", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.CicloPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CiclosPago", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("CodigoCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UsuarioEjecutivoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCliente")
                        .IsUnique();

                    b.HasIndex("NumeroDocumento")
                        .IsUnique();

                    b.HasIndex("UsuarioEjecutivoId");

                    b.ToTable("Clientes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Clientes_TipoPersona", "\"TipoPersona\" IN ('Natural', 'Juridica')");
                        });
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ClienteBeneficiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("DUI")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoRelacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ClienteId", "Estado")
                        .HasFilter("\"Estado\" = 'Activo'");

                    b.ToTable("ClientesBeneficiarios", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ClienteBeneficiarioHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteBeneficiarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("DUI")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("PorcentajeAsignado")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("TipoRelacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteBeneficiarioId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FechaEvento");

                    b.ToTable("ClientesBeneficiariosHistorico", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ClienteCuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BancoId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsPrincipal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoCuenta")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BancoId");

                    b.HasIndex("ClienteId")
                        .IsUnique()
                        .HasFilter("\"EsPrincipal\" = TRUE");

                    b.ToTable("ClienteCuentas", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ConfiguracionContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CapitalBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<decimal>("PorcentajeMensual")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId", "FechaInicio");

                    b.ToTable("ConfiguracionContrato", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ConfiguracionCortePago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ConfiguracionSistemaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionSistemaId");

                    b.ToTable("ConfiguracionCortesPago", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ConfiguracionSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("AplicarReglaAnioBisiesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("ComisionEmpresaPorcentaje")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(5m);

                    b.Property<int>("DiasCuatrimestreBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(120);

                    b.Property<int>("DiasMesBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("UsarDiasExactosPrimerCuatrimestre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionSistema", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CapitalActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CapitalInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ComisionRetiro")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("ModalidadRendimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroContrato")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PermiteUnificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("PorcentajeMensual")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Estado");

                    b.HasIndex("NumeroContrato")
                        .IsUnique();

                    b.ToTable("Contratos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Contratos_CapitalActual", "\"CapitalActual\" >= 0");

                            t.HasCheckConstraint("CK_Contratos_CapitalInicial", "\"CapitalInicial\" > 0");

                            t.HasCheckConstraint("CK_Contratos_Estado", "\"Estado\" IN ('Activo', 'Finalizado', 'Unificado', 'Anulado')");

                            t.HasCheckConstraint("CK_Contratos_ModalidadRendimiento", "\"ModalidadRendimiento\" IN ('Normal', 'InteresCompuesto')");
                        });
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ContratoBeneficiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteBeneficiarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PorcentajeAsignado")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteBeneficiarioId");

                    b.HasIndex("ContratoId");

                    b.ToTable("ContratoBeneficiarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContratoBeneficiarios_Porcentaje", "\"PorcentajeAsignado\" >= 0 AND \"PorcentajeAsignado\" <= 100");
                        });
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ContratoRelacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("ContratoOrigenId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaRelacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("GrupoOperacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("MontoTransferido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TipoRelacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContratoDestinoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ContratoOrigenId", "ContratoDestinoId", "FechaRelacion");

                    b.ToTable("ContratoRelaciones", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.DecisionPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaDecision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("MetodoRetiro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("MontoAInteresCompuesto")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("MontoReinvertido")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("MontoRetirado")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PagoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoDecision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PagoId");

                    b.ToTable("DecisionesPago", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.FechaCortePago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfiguracionCortePagoId")
                        .HasColumnType("integer");

                    b.Property<int>("Dia")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionCortePagoId", "Orden")
                        .IsUnique();

                    b.HasIndex("ConfiguracionCortePagoId", "Mes", "Dia")
                        .IsUnique();

                    b.ToTable("FechasCortePago", null, t =>
                        {
                            t.HasCheckConstraint("CK_FechasCortePago_Dia", "\"Dia\" BETWEEN 1 AND 31");
                        });
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.MovimientoContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CicloPagoId")
                        .HasColumnType("integer");

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CicloPagoId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimientosContrato", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BancoId")
                        .HasColumnType("integer");

                    b.Property<int>("CalculoPagoId")
                        .HasColumnType("integer");

                    b.Property<int>("CicloPagoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClienteCuentaId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ComisionAplicada")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("DiasPagados")
                        .HasColumnType("integer");

                    b.Property<int?>("EjecutadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("FechaFinCalculo")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaInicioCalculo")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GananciaBruta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ModalidadRendimientoAlCierre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("MontoEntregado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BancoId");

                    b.HasIndex("CalculoPagoId")
                        .IsUnique();

                    b.HasIndex("CicloPagoId");

                    b.HasIndex("ClienteCuentaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EjecutadoPor");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.PlanPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CicloPagoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CicloPagoId");

                    b.ToTable("PlanesPago", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ReglaPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<decimal>("MontoMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MontoMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PlanPagoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PlanPagoId");

                    b.ToTable("ReglasPago", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReglasPago_MontoMax", "\"MontoMax\" >= \"MontoMin\"");
                        });
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.AgendaPago", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.CicloPago", "CicloPago")
                        .WithMany("AgendaPagos")
                        .HasForeignKey("CicloPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tradecorp.Domain.Models.Entities.Cliente", "Cliente")
                        .WithMany("AgendaPagos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CicloPago");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.AsignacionDetalle", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.AsignacionPago", "Asignacion")
                        .WithMany("Detalles")
                        .HasForeignKey("AsignacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tradecorp.Domain.Models.Entities.Pago", "Pago")
                        .WithOne("AsignacionDetalle")
                        .HasForeignKey("Tradecorp.Domain.Models.Entities.AsignacionDetalle", "PagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asignacion");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.AsignacionPago", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.Banco", "Banco")
                        .WithMany("AsignacionesPago")
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tradecorp.Domain.Models.Entities.CicloPago", "CicloPago")
                        .WithMany("AsignacionesPago")
                        .HasForeignKey("CicloPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tradecorp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany("AsignacionesPago")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Banco");

                    b.Navigation("CicloPago");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.AuditoriaContrato", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tradecorp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contrato");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.CalculoPago", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.CicloPago", "CicloPago")
                        .WithMany("CalculosPago")
                        .HasForeignKey("CicloPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tradecorp.Domain.Models.Entities.Contrato", "Contrato")
                        .WithMany("CalculosPago")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CicloPago");

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.Cliente", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.Usuario", "UsuarioEjecutivo")
                        .WithMany("ClientesAsignados")
                        .HasForeignKey("UsuarioEjecutivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioEjecutivo");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ClienteBeneficiario", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.Cliente", "Cliente")
                        .WithMany("Beneficiarios")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ClienteBeneficiarioHistorico", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.ClienteBeneficiario", "ClienteBeneficiario")
                        .WithMany("Historico")
                        .HasForeignKey("ClienteBeneficiarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tradecorp.Domain.Models.Entities.Cliente", "Cliente")
                        .WithMany("BeneficiariosHistorico")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ClienteBeneficiario");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ClienteCuenta", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.Banco", "Banco")
                        .WithMany("ClienteCuentas")
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tradecorp.Domain.Models.Entities.Cliente", "Cliente")
                        .WithMany("ClienteCuentas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Banco");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ConfiguracionContrato", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.Contrato", "Contrato")
                        .WithMany("ConfiguracionesContrato")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ConfiguracionCortePago", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.ConfiguracionSistema", "ConfiguracionSistema")
                        .WithMany("CortesPago")
                        .HasForeignKey("ConfiguracionSistemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfiguracionSistema");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.Contrato", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ContratoBeneficiario", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.ClienteBeneficiario", "ClienteBeneficiario")
                        .WithMany()
                        .HasForeignKey("ClienteBeneficiarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tradecorp.Domain.Models.Entities.Contrato", "Contrato")
                        .WithMany("Beneficiarios")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClienteBeneficiario");

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ContratoRelacion", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.Contrato", "ContratoDestino")
                        .WithMany("RelacionesComoDestino")
                        .HasForeignKey("ContratoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tradecorp.Domain.Models.Entities.Contrato", "ContratoOrigen")
                        .WithMany("RelacionesComoOrigen")
                        .HasForeignKey("ContratoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tradecorp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany("RelacionesContratoEjecutadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContratoDestino");

                    b.Navigation("ContratoOrigen");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.DecisionPago", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.Pago", "Pago")
                        .WithMany("Decisiones")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.FechaCortePago", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.ConfiguracionCortePago", "ConfiguracionCortePago")
                        .WithMany("FechasCorte")
                        .HasForeignKey("ConfiguracionCortePagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfiguracionCortePago");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.MovimientoContrato", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.CicloPago", "CicloPago")
                        .WithMany("MovimientosContrato")
                        .HasForeignKey("CicloPagoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tradecorp.Domain.Models.Entities.Contrato", "Contrato")
                        .WithMany("MovimientosContrato")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tradecorp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany("MovimientosContrato")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CicloPago");

                    b.Navigation("Contrato");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.Pago", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.Banco", "Banco")
                        .WithMany("Pagos")
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tradecorp.Domain.Models.Entities.CalculoPago", "CalculoPago")
                        .WithOne("Pago")
                        .HasForeignKey("Tradecorp.Domain.Models.Entities.Pago", "CalculoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tradecorp.Domain.Models.Entities.CicloPago", "CicloPago")
                        .WithMany("Pagos")
                        .HasForeignKey("CicloPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tradecorp.Domain.Models.Entities.ClienteCuenta", "ClienteCuenta")
                        .WithMany("Pagos")
                        .HasForeignKey("ClienteCuentaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tradecorp.Domain.Models.Entities.Cliente", "Cliente")
                        .WithMany("Pagos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tradecorp.Domain.Models.Entities.Usuario", "UsuarioEjecutadoPor")
                        .WithMany("PagosEjecutados")
                        .HasForeignKey("EjecutadoPor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Banco");

                    b.Navigation("CalculoPago");

                    b.Navigation("CicloPago");

                    b.Navigation("Cliente");

                    b.Navigation("ClienteCuenta");

                    b.Navigation("UsuarioEjecutadoPor");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.PlanPago", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.CicloPago", "CicloPago")
                        .WithMany("PlanesPago")
                        .HasForeignKey("CicloPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CicloPago");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ReglaPago", b =>
                {
                    b.HasOne("Tradecorp.Domain.Models.Entities.PlanPago", "PlanPago")
                        .WithMany("ReglasPago")
                        .HasForeignKey("PlanPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanPago");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.AsignacionPago", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.Banco", b =>
                {
                    b.Navigation("AsignacionesPago");

                    b.Navigation("ClienteCuentas");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.CalculoPago", b =>
                {
                    b.Navigation("Pago");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.CicloPago", b =>
                {
                    b.Navigation("AgendaPagos");

                    b.Navigation("AsignacionesPago");

                    b.Navigation("CalculosPago");

                    b.Navigation("MovimientosContrato");

                    b.Navigation("Pagos");

                    b.Navigation("PlanesPago");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.Cliente", b =>
                {
                    b.Navigation("AgendaPagos");

                    b.Navigation("Beneficiarios");

                    b.Navigation("BeneficiariosHistorico");

                    b.Navigation("ClienteCuentas");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ClienteBeneficiario", b =>
                {
                    b.Navigation("Historico");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ClienteCuenta", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ConfiguracionCortePago", b =>
                {
                    b.Navigation("FechasCorte");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.ConfiguracionSistema", b =>
                {
                    b.Navigation("CortesPago");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.Contrato", b =>
                {
                    b.Navigation("Beneficiarios");

                    b.Navigation("CalculosPago");

                    b.Navigation("ConfiguracionesContrato");

                    b.Navigation("MovimientosContrato");

                    b.Navigation("RelacionesComoDestino");

                    b.Navigation("RelacionesComoOrigen");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.Pago", b =>
                {
                    b.Navigation("AsignacionDetalle");

                    b.Navigation("Decisiones");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.PlanPago", b =>
                {
                    b.Navigation("ReglasPago");
                });

            modelBuilder.Entity("Tradecorp.Domain.Models.Entities.Usuario", b =>
                {
                    b.Navigation("AsignacionesPago");

                    b.Navigation("ClientesAsignados");

                    b.Navigation("MovimientosContrato");

                    b.Navigation("PagosEjecutados");

                    b.Navigation("RelacionesContratoEjecutadas");
                });
#pragma warning restore 612, 618
        }
    }
}
